trigger:
- master 

steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'ServiceConnectionAzureSonar'
    scannerMode: 'MSBuild'
    projectKey: 'MyTokenName'
    projectName: 'MyShuttle'

# Run Code Analysis task
- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'