# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'


steps:


- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'ServiceConnectionAzureSonar'
    scannerMode: 'MSBuild'
    projectKey: 'MyTokenName'
    projectName: 'MyShuttle'


- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
